name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
  workflow_call:
    inputs:
      pr_number:
        description: Pull request number to review when the workflow is reused.
        type: string
        default: ""
        required: false
      repo_name:
        description: Optional repository (owner/name) override for the PR.
        required: false
        type: string
    secrets:
      OPENAI_API_KEY:
        required: true

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai-code-review:
    name: OpenAI Code Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository under review
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resolve review context
        id: review-context
        run: |
          set -euo pipefail

          if [ "${EVENT_NAME}" = "pull_request" ]; then
            echo "pr-number=${PR_CONTEXT_NUMBER}" >> "$GITHUB_OUTPUT"
            echo "repo-name=${DEFAULT_REPO}" >> "$GITHUB_OUTPUT"
          else
            if [ -z "${PR_NUMBER_INPUT}" ]; then
              echo "::error::'pr_number' input is required when reusing this workflow."
              exit 1
            fi

            echo "pr-number=${PR_NUMBER_INPUT}" >> "$GITHUB_OUTPUT"

            if [ -n "${REPO_NAME_INPUT}" ]; then
              echo "repo-name=${REPO_NAME_INPUT}" >> "$GITHUB_OUTPUT"
            else
              echo "repo-name=${DEFAULT_REPO}" >> "$GITHUB_OUTPUT"
            fi
          fi
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_CONTEXT_NUMBER: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || '' }}
          DEFAULT_REPO: ${{ github.repository }}
          PR_NUMBER_INPUT: ${{ inputs.pr_number }}
          REPO_NAME_INPUT: ${{ inputs.repo_name }}

      - name: Resolve workflow source
        id: workflow-source
        run: |
          set -euo pipefail

          ref="${WORKFLOW_REF#*@}"
          path_without_ref="${WORKFLOW_REF%@*}"
          repo="${path_without_ref%%/.github/workflows/*}"

          echo "ref=${ref}" >> "$GITHUB_OUTPUT"
          echo "repo=${repo}" >> "$GITHUB_OUTPUT"
          ref_name="$ref"
          if [[ "$ref_name" == refs/heads/* ]]; then
            ref_name="${ref_name#refs/heads/}"
          elif [[ "$ref_name" == refs/tags/* ]]; then
            ref_name="${ref_name#refs/tags/}"
          fi
          echo "ref-name=${ref_name}" >> "$GITHUB_OUTPUT"
        env:
          WORKFLOW_REF: ${{ github.workflow_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests PyGithub

      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.review-context.outputs.pr-number }}
          REPO_NAME: ${{ steps.review-context.outputs.repo-name }}
          WORKFLOW_REPO: ${{ steps.workflow-source.outputs.repo }}
          WORKFLOW_REF: ${{ steps.workflow-source.outputs.ref }}
          WORKFLOW_REF_NAME: ${{ steps.workflow-source.outputs.ref-name }}
          SCRIPT_PATH: scripts/python/ai-code-review.py
        run: |
          set -euo pipefail

          echo "Current directory: $(pwd)"
          echo "Files in current directory:" 
          ls -la

          if [ ! -f "$SCRIPT_PATH" ]; then
            echo "::error::Reviewer script not found at ${SCRIPT_PATH}."
            echo "Make sure the 'Checkout workflow utilities' step has access to ${WORKFLOW_REPO}@${WORKFLOW_REF_NAME:-${WORKFLOW_REF}}."
            echo "Tip: provide a token with read access via the GITHUB_TOKEN secret (for checkout) or REVIEW_BOT_TOKEN secret (for API calls) when consuming this workflow from another repository."
            echo "Workspace layout (depth 3):"
            find . -maxdepth 3 -type f -name 'ai-code-review.py' || true
            exit 1
          fi

          echo "Using reviewer script at: $SCRIPT_PATH"
          python "$SCRIPT_PATH"

      - name: Comment summary on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REVIEW_BOT_TOKEN != '' && secrets.REVIEW_BOT_TOKEN || github.token }}
          script: |
            const fs = require('fs');
            const summaryPath = 'review-summary.md';

            if (fs.existsSync(summaryPath)) {
              const summary = fs.readFileSync(summaryPath, 'utf8').trim();
              if (summary.length > 0) {
                const [owner, repo] = '${{ steps.review-context.outputs.repo-name }}'.split('/');
                const issueNumber = Number('${{ steps.review-context.outputs.pr-number }}');

                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: issueNumber,
                  body: summary
                });
              }
            }

      - name: Upload review results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-review-results
          path: |
            review-summary.md
            review-details.json
          if-no-files-found: ignore
          retention-days: 30
