name: AI Code Review Runner
description: Runs the reusable AI code review script with required dependencies.
inputs:
  openai_api_key:
    description: OpenAI API key used by the reviewer.
    required: true
  github_token:
    description: Token used for GitHub API access.
    required: true
  pr_number:
    description: Pull request number under review.
    required: true
  repo_name:
    description: Repository (owner/name) containing the PR.
    required: true
  python-version:
    description: Python runtime version.
    required: false
    default: '3.11'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install openai requests PyGithub

    - name: Execute AI Code Review
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ inputs.pr_number }}
        REPO_NAME: ${{ inputs.repo_name }}
      run: |
        python "${{ github.action_path }}/../../../scripts/python/ai-code-review.py"
